<p>Due to breaking changes in the Jest library, we will need to modify our tests to avoid the following errors:</p><p><em>Test functions cannot both take a 'done' callback and return something. Either use a 'done' callback, or return a promise.</em></p><p>This was first raised in the QA <a href="https://www.udemy.com/course/nestjs-the-complete-developers-guide/learn/lecture/27443114#questions/15456608" rel="noopener noreferrer" target="_blank">here</a>.</p><p>Find the <strong>src/users/auth.service.spec.ts </strong>file and make the following changes:</p><p>1) Ensure that the import has been updated:</p><pre class="prettyprint linenums">import { BadRequestException, NotFoundException } from '@nestjs/common';</pre><p><br></p><p>2) Refactor <strong>'throws if an invalid password is provided'</strong> test to remove try/catch and done callback:</p><pre class="prettyprint linenums">  it('throws if an invalid password is provided', async () =&gt; {
    fakeUsersService.find = () =&gt;
      Promise.resolve([
        { email: 'asdf@asdf.com', password: 'laskdjf' } as User,
      ]);
    await expect(
      service.signin('laskdjf@alskdfj.com', 'passowrd'),
    ).rejects.toThrow(BadRequestException);
  });</pre>